### ISSUE TITLE
Cannot be built on Windows with VS2017

### ISSUE THREAD

**Issue by ridethepig** [Winnerhust/inifile2#13]
Strange Problems occurred.
It seems like that the code file has some strange characters, causing encoding problems......
Such as following:
> warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss

then it's followed by a series of unreasonable errors

> 1>c:\users\proto\desktop\inifile2-master\test1\test1\inifile.cpp(64): warning C4101: 'newSection': unreferenced local variable
1>c:\users\proto\desktop\inifile2-master\test1\test1\inifile.cpp(80): error C2065: 's': undeclared identifier
1>c:\users\proto\desktop\inifile2-master\test1\test1\inifile.cpp(80): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\proto\desktop\inifile2-master\test1\test1\inifile.cpp(83): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\proto\desktop\inifile2-master\test1\test1\inifile.cpp(83): error C2065: 's': undeclared identifier

This is just a reminder, since I have found an alternative.

**Comment by y11en** [comment]
same as above

**Comment by Winnerhust** [comment]
文件的编码默认是UTF8,你的环境需要的文件编码是936，对应的是GBK或者GB2312,你把inifile.cpp和inifile.h的编码格式改成GB2312应该就可以了
