### ISSUE TITLE
格式不正确时 会崩溃。

### ISSUE THREAD

**Issue by vincent-coding** [Winnerhust/inifile2#2]
[test]
key=1 '测试

**Comment by vincent-coding** [comment]
崩溃的原因是中文。。

**Comment by vincent-coding** [comment]
解决办法是：
将trim函数中的isspace 换成c++的isspace(ch,loc)：
std::locale loc;
std::isspace(str[i],loc)

**Comment by Winnerhust** [comment]
多谢你的建议
这应该是个bug，之前的版本不支持
```
key = 1 #注释
```
这种后面带注释的行
现在已经修复了，读取该行后,解析得到的是
line:"key=1'
comment："#注释“

需要注意的是，这种后缀格式的行再使用saveas 函数进行保存到其他文件的的话会转成
```
#注释
key=1
```
