### ISSUE TITLE
vs2010中，trim字符串访问越界

### ISSUE THREAD

**Issue by refluxwhw** [Winnerhust/inifile2#5]
我在vs2010中调试发现在读一个utf8无bom格式编码文件时，在load中getline读空行时返回为1，line="",line.size=0,line.capacity=15;然后进入trim函数中，str为空字符串，str[0]访问越界。

我又在qt中和linux下测试了，都没有越界。

vs 中字符串有点不一样，空串没有'\0'结束符

vs2010下我只能修改trim

```
while (i<len && isspace(str[i]) && str[i] != '\0') {
    i++;
}
```

**Comment by tangfuyuan** [comment]
C++11，string字符串都是以'\0'结尾，我用vs2015，没发现越界的问题，但为了兼容性考虑，用len判断字符串结束更合适

**Comment by refluxwhw** [comment]
已经很久了，当时也不是C++11。使用VS2015 C++11，没有出现问题，可以关闭
