### ISSUE TITLE
vector迭代过程中的erase操作

### ISSUE THREAD

**Issue by llgithubll** [Winnerhust/inifile2#7]
```
void IniFile::deleteKey(const string &section, const string &key)
{
    IniSection *sect = getSection(section);

    if (sect != NULL) {
        for (IniSection::iterator it = sect->begin(); it != sect->end(); ++it) {
            if (it->key == key) {
                sect->items.erase(it);
                break;
            }
        }
    }

}
```
这个deleteKey函数是在section中删除键为key的键值对，当有重复的键值对时，不能删除彻底。
而且，在vector迭代过程中进行erase操作，不是会造成迭代器失效吗？O(∩_∩)O~

**Comment by tangfuyuan** [comment]
1. 关于重复键值对：ini文件本身就不应该存在重复的键值对，问题不在于deleteKey这里，而是在load时应检测key键名是否重复，如果重复应做忽略或覆盖处理。
2.上述代码中， vector迭代过程中erase之后直接break跳出for循环了，虽然迭代器变成野指针，但并不会影响deleteKey本身的运行。如有强迫症，可以修改为it = sect->items.erase(it); 且 ++it 要移入else分支

**Comment by llgithubll** [comment]
谢谢.
