### ISSUE TITLE
vs2013 下面测试使用有问题 

### ISSUE THREAD

**Issue by yueswing07** [Winnerhust/inifile2#9]
vs2013 下面我写的测试代码函数  在ini.getValue("", "USER", value);函数出会有0xC0000005: Access violation reading location 0xCCCCCCD0.错误   我看了下代码没看出来  
还有源码文件inifile.cpp 里面 我发现new IniSection(); 会有问题  结构体用new 是否通用？ 
我修改了下用变量定义
	//section = new IniSection();
	IniSection tmp;
	section = &tmp;

void IniFileTest(){
    // write config 
    char filepath[] = "./IniTest.ini";
    FILE *fp = fopen(filepath, "w");
    char content[] = " USER=root \r\n [COMMON] \n DB=sys      \nPASSWD=tt \nPASSWD=dd  \n#commit   \n ;--------- \n[DEFINE] \nname=cxy\nvalue=1 #test";
    fwrite(content, sizeof(char), strlen(content), fp);
    fclose(fp);
    // read config
    IniFile ini;
    ini.load(filepath);
    string value;
    vector<string> valueList;
    ini.getValue("", "USER", value);
    cout << value;
    ini.getValue("COMMON", "DB", value);
    cout << value;
    ini.getValues("COMMON", "PASSWD", valueList);
    for (vector<string>::iterator i = valueList.begin(); i < valueList.end(); i++){
        cout << *i;
    }
    ini.getValue("DEFINE", "name", value);
    cout << value;
    ini.getValue("DEFINE", "value", value);
    cout << value;

    // update config
    ini.setValue("COMMON", "PASSWD", "root", "数据库密码");

    // delete config
    ini.deleteKey("COMMON", "DB");

#ifdef _DEBUG
    printf("IniFileTest end any key continue .. ");
    getchar();
#endif
}

**Comment by Winnerhust** [comment]
https://github.com/Winnerhust/inifile2/commit/01646711c5ef3831361b7cb67588f4d61d2e2810

测试用例最新版本已验证通过
